version: '3.8'

services:
  # Servidor PHP
  php-fpm:
    build:
      args:
        user: ${SO_USER}
        uid: 1000
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php8.1.ini:/usr/local/etc/php/php.ini
    networks:
      - laravelnet

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - laravelnet

  ### PostgreSQL Server Container ##################################
  db_postgres:
    build:
      context: ./docker/postgres
    restart: unless-stopped
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge

volumes:
  db-postgres:
    driver: local
